// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rdb_protocol/ql2_extensions.proto

package ql2.extension;

public final class Ql2Extensions {
  private Ql2Extensions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(ql2.extension.Ql2Extensions.backtrace);
  }
  public static final int BACKTRACE_FIELD_NUMBER = 10000;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      ql2.Ql2.Term,
      ql2.Ql2.Backtrace> backtrace = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        ql2.Ql2.Backtrace.class,
        ql2.Ql2.Backtrace.getDefaultInstance());
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!rdb_protocol/ql2_extensions.proto\022\rql2" +
      ".extension\032\026rdb_protocol/ql2.proto:-\n\tba" +
      "cktrace\022\t.ql2.Term\030\220N \002(\0132\016.ql2.Backtrac" +
      "e"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          backtrace.internalInit(descriptor.getExtensions().get(0));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ql2.Ql2.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
